# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-26 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='utest',
            field=models.CharField(default=18800126050, max_length=11),
            preserve_default=False,
        ),
    ]
