# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-25 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('description', models.TextField(verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='游客', max_length=256, verbose_name='评论人')),
                ('description', models.TextField(verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('classification', models.IntegerField(choices=[(1, '女装'), (2, '男装'), (3, '内衣'), (4, '鞋靴'), (5, '其他')], verbose_name='分类')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('has_sale', models.IntegerField(default=0, verbose_name='付款人数')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('price', models.FloatField(max_length=100, verbose_name='价格')),
                ('counts', models.IntegerField(db_column='counts', verbose_name='库存')),
                ('phone', models.CharField(max_length=11, verbose_name='卖家手机号')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True, verbose_name='订单编号')),
                ('status', models.IntegerField(choices=[(-1, '支付失败'), (1, '已支付'), (3, '已发货')], default=0, verbose_name='状态')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('price', models.FloatField(verbose_name='总价格')),
                ('address', models.CharField(default='', max_length=256, verbose_name='交易地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人手机号')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('good_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.Item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
                'db_table': 'market_order',
            },
        ),
        migrations.AddField(
            model_name='commentdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='market.OrderModel'),
        ),
        migrations.AddField(
            model_name='commentdetailmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
