# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gtext', models.CharField(max_length=140)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gtype',
        ),
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
