# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-25 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20200626_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodinfo',
            name='gtype',
        ),
        migrations.DeleteModel(
            name='GoodInfo',
        ),
    ]
